/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsoftware;

/**
 *
 * @author Muhammad
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame3 = new javax.swing.JInternalFrame();
        issueBook = new javax.swing.JButton();
        addMem = new javax.swing.JButton();
        removeMem = new javax.swing.JButton();
        getDetails = new javax.swing.JButton();
        showAllMem = new javax.swing.JButton();
        updateMem = new javax.swing.JButton();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        addBook = new javax.swing.JButton();
        removeBook = new javax.swing.JButton();
        updateBook = new javax.swing.JButton();
        allBooks = new javax.swing.JButton();
        availBooks = new javax.swing.JButton();
        issuedBooks = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame3.setTitle("Members");
        jInternalFrame3.setVisible(true);

        issueBook.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        issueBook.setText("Issue Book");
        issueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookActionPerformed(evt);
            }
        });

        addMem.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        addMem.setText("Add Member");
        addMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemActionPerformed(evt);
            }
        });

        removeMem.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        removeMem.setText("Remove Member");
        removeMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMemActionPerformed(evt);
            }
        });

        getDetails.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getDetails.setText("Get Details");
        getDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDetailsActionPerformed(evt);
            }
        });

        showAllMem.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        showAllMem.setText("Show All Members");
        showAllMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllMemActionPerformed(evt);
            }
        });

        updateMem.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        updateMem.setText("Update Member");
        updateMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(issueBook, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeMem))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addComponent(updateMem, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(showAllMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(issueBook, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addMem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeMem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateMem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showAllMem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jInternalFrame4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jInternalFrame4.setTitle("Books");
        jInternalFrame4.setVisible(true);

        addBook.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        addBook.setText("Add Book");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });

        removeBook.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        removeBook.setText("Remove Book");
        removeBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBookActionPerformed(evt);
            }
        });

        updateBook.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        updateBook.setText("Update Book");
        updateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookActionPerformed(evt);
            }
        });

        allBooks.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        allBooks.setText("All Books");
        allBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBooksActionPerformed(evt);
            }
        });

        availBooks.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        availBooks.setText("Available Books");
        availBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availBooksActionPerformed(evt);
            }
        });

        issuedBooks.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        issuedBooks.setText("Issued Books");
        issuedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedBooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addComponent(addBook, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeBook, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jInternalFrame4Layout.createSequentialGroup()
                        .addComponent(allBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(availBooks)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(issuedBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBook, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBook, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame3)
            .addComponent(jInternalFrame4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jInternalFrame4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jInternalFrame3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        addBook add = new addBook();
        add.setVisible(true);
        System.out.println("Form Opened -> addBook");
    }//GEN-LAST:event_addBookActionPerformed

    private void removeBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBookActionPerformed
        removeBook remove = new removeBook();
        remove.setVisible(true);
        System.out.println("Form Opened -> removeBook");
    }//GEN-LAST:event_removeBookActionPerformed

    private void updateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookActionPerformed
        updateBook update = new updateBook();
        update.setVisible(true);
        System.out.println("Form Opened -> updateBook");
    }//GEN-LAST:event_updateBookActionPerformed

    private void allBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBooksActionPerformed
        allBooks all = new allBooks();
        all.setVisible(true);
        System.out.println("Form Opened -> allBooks");
    }//GEN-LAST:event_allBooksActionPerformed

    private void availBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availBooksActionPerformed
        availableBooks available = new availableBooks();
        available.setVisible(true);
        System.out.println("Form Opened -> availableBooks");
    }//GEN-LAST:event_availBooksActionPerformed

    private void issuedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedBooksActionPerformed
        issuedBooks issued = new issuedBooks();
        issued.setVisible(true);
        System.out.println("Form Opened -> issuedBooks");
    }//GEN-LAST:event_issuedBooksActionPerformed

    private void issueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookActionPerformed
        issueBook issue = new issueBook();
        issue.setVisible(true);
        System.out.println("Form Opened -> issueBook");
    }//GEN-LAST:event_issueBookActionPerformed

    private void addMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemActionPerformed
        addMember addmember = new addMember();
        addmember.setVisible(true);
        System.out.println("Form Opened -> addMember");
    }//GEN-LAST:event_addMemActionPerformed

    private void removeMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMemActionPerformed
        removeMember removemember = new removeMember();
        removemember.setVisible(true);
        System.out.println("Form Opened -> removeMember");
    }//GEN-LAST:event_removeMemActionPerformed

    private void updateMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMemActionPerformed
        updateMember update = new updateMember();
        update.setVisible(true);
        System.out.println("Form Opened -> updateMember");
    }//GEN-LAST:event_updateMemActionPerformed

    private void showAllMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllMemActionPerformed
        showAllMembers allmembers = new showAllMembers();
        allmembers.setVisible(true);
        System.out.println("Form Opened -> showAllMembers");
    }//GEN-LAST:event_showAllMemActionPerformed

    private void getDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDetailsActionPerformed
        getDetails getdetails = new getDetails();
        getdetails.setVisible(true);
        System.out.println("Form Opened -> getDetails");
    }//GEN-LAST:event_getDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBook;
    private javax.swing.JButton addMem;
    private javax.swing.JButton allBooks;
    private javax.swing.JButton availBooks;
    private javax.swing.JButton getDetails;
    private javax.swing.JButton issueBook;
    private javax.swing.JButton issuedBooks;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JButton removeBook;
    private javax.swing.JButton removeMem;
    private javax.swing.JButton showAllMem;
    private javax.swing.JButton updateBook;
    private javax.swing.JButton updateMem;
    // End of variables declaration//GEN-END:variables
}
