/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package librarymanagementsoftware;

/**
 *
 * @author muham_000
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        addBook = new javax.swing.JButton();
        removeBook = new javax.swing.JButton();
        updateBook = new javax.swing.JButton();
        issuedBooks = new javax.swing.JButton();
        availBooks = new javax.swing.JButton();
        allBooks = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        issueBook = new javax.swing.JButton();
        addMem = new javax.swing.JButton();
        removeMem = new javax.swing.JButton();
        updateMem = new javax.swing.JButton();
        showAllMem = new javax.swing.JButton();
        getDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libri");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N

        addBook.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        addBook.setText("Add Book");
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });

        removeBook.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        removeBook.setText("Remove Book");
        removeBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBookActionPerformed(evt);
            }
        });

        updateBook.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        updateBook.setText("Update Book");
        updateBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBookActionPerformed(evt);
            }
        });

        issuedBooks.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        issuedBooks.setText("Issued Books");
        issuedBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issuedBooksActionPerformed(evt);
            }
        });

        availBooks.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        availBooks.setText("Available Books");
        availBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availBooksActionPerformed(evt);
            }
        });

        allBooks.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        allBooks.setText("All Books");
        allBooks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBooksActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(allBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeBook, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(updateBook, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(availBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBook, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBook, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBook, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(availBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(allBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issuedBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Books", jPanel1);

        issueBook.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        issueBook.setText("Issue Book");
        issueBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                issueBookActionPerformed(evt);
            }
        });

        addMem.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        addMem.setText("Add Member");
        addMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemActionPerformed(evt);
            }
        });

        removeMem.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        removeMem.setText("Remove Member");
        removeMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMemActionPerformed(evt);
            }
        });

        updateMem.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        updateMem.setText("Update Member");
        updateMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMemActionPerformed(evt);
            }
        });

        showAllMem.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        showAllMem.setText("Show All Members");
        showAllMem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllMemActionPerformed(evt);
            }
        });

        getDetails.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        getDetails.setText("Get Details");
        getDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(showAllMem, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(issueBook, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(removeMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateMem, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(addMem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(getDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showAllMem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(issueBook, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeMem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateMem, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Members", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        addBook add = new addBook();
        add.setVisible(true);
        System.out.println("Form Opened -> addBook");
    }//GEN-LAST:event_addBookActionPerformed

    private void removeBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBookActionPerformed
        removeBook remove = new removeBook();
        remove.setVisible(true);
        System.out.println("Form Opened -> removeBook");
    }//GEN-LAST:event_removeBookActionPerformed

    private void updateBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBookActionPerformed
        updateBook update = new updateBook();
        update.setVisible(true);
        System.out.println("Form Opened -> updateBook");
    }//GEN-LAST:event_updateBookActionPerformed

    private void issuedBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issuedBooksActionPerformed
        issuedBooks issued = new issuedBooks();
        issued.setVisible(true);
        System.out.println("Form Opened -> issuedBooks");
    }//GEN-LAST:event_issuedBooksActionPerformed

    private void availBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availBooksActionPerformed
        availableBooks available = new availableBooks();
        available.setVisible(true);
        System.out.println("Form Opened -> availableBooks");
    }//GEN-LAST:event_availBooksActionPerformed

    private void allBooksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBooksActionPerformed
        allBooks all = new allBooks();
        all.setVisible(true);
        System.out.println("Form Opened -> allBooks");
    }//GEN-LAST:event_allBooksActionPerformed

    private void issueBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_issueBookActionPerformed
        issueBook issue = new issueBook();
        issue.setVisible(true);
        System.out.println("Form Opened -> issueBook");
    }//GEN-LAST:event_issueBookActionPerformed

    private void addMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemActionPerformed
        addMember addmember = new addMember();
        addmember.setVisible(true);
        System.out.println("Form Opened -> addMember");
    }//GEN-LAST:event_addMemActionPerformed

    private void removeMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMemActionPerformed
        removeMember removemember = new removeMember();
        removemember.setVisible(true);
        System.out.println("Form Opened -> removeMember");
    }//GEN-LAST:event_removeMemActionPerformed

    private void updateMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMemActionPerformed
        updateMember update = new updateMember();
        update.setVisible(true);
        System.out.println("Form Opened -> updateMember");
    }//GEN-LAST:event_updateMemActionPerformed

    private void showAllMemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllMemActionPerformed
        showAllMembers allmembers = new showAllMembers();
        allmembers.setVisible(true);
        System.out.println("Form Opened -> showAllMembers");
    }//GEN-LAST:event_showAllMemActionPerformed

    private void getDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getDetailsActionPerformed
        getDetails getdetails = new getDetails();
        getdetails.setVisible(true);
        System.out.println("Form Opened -> getDetails");
    }//GEN-LAST:event_getDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBook;
    private javax.swing.JButton addMem;
    private javax.swing.JButton allBooks;
    private javax.swing.JButton availBooks;
    private javax.swing.JButton getDetails;
    private javax.swing.JButton issueBook;
    private javax.swing.JButton issuedBooks;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton removeBook;
    private javax.swing.JButton removeMem;
    private javax.swing.JButton showAllMem;
    private javax.swing.JButton updateBook;
    private javax.swing.JButton updateMem;
    // End of variables declaration//GEN-END:variables
}
